# Generated by Django 4.0.1 on 2022-01-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='foto_perfil',
            new_name='image',
        ),
    ]
