# Generated by Django 4.0.1 on 2022-01-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_imagen_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=5000, upload_to='uploads'),
        ),
    ]
