# Generated by Django 4.0.1 on 2022-01-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='megusta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
